num1=int(input("Enter first number:"))
num2=int(input("Enter second number:"))

print("1.Sum of ",num1,"&",num2,"=",num1+num2)
print("2.subtracting ",num1,"from",num2,"=",num1-num2)
print("3.multiplication of ",num1,"&",num2,"=",num1*num2)
print("4.dividing ",num1,"with",num2,"=",num1/num2)
print("5.Floor Division // of ",num1,"with",num2,"=",num1//num2)
print("6.Reminder of ",num1,"with",num2,"=",num1%num2)
print("7.Exponent of ",num1,"to",num2,"=",num1**num2)