print("We are going to use all comparison operators here to compare 2 numbers")
var1=int(input("Enter number1:"))
var2=int(input("Enter number2:"))
print('1. Two numbers are equal or not:', var1 == var2)    
print('2. Two numbers are not equal or not:', var1 != var2)    
print('3. var1 is less than or equal to var2:', var1 <= var2)    
print('4. var1 is greater than or equal to var2:', var1 >= var2)    
print('5. var1 is greater var2:', var1 > var2)    
print('6. var1 is less than var2:', var1< var2)   